### ISSUE TITLE
Using networkx graph format

### ISSUE THREAD

**Issue by cli0** [ysig/GraKeL#10]
Is there any way to use networkx graph format or do you have some function to transform .gexf formats to the appropriate format for the library?

**Comment by ysig** [comment]
Hi,

[As you can see inside the API](https://ysig.github.io/GraKeL/dev/classes.html#load-from-other-file-formats) (after version 0.1a5) there are some utility function concerning input transformation from other formats, one of which is [networkx](https://ysig.github.io/GraKeL/dev/generated/grakel.graph_from_networkx.html#grakel.graph_from_networkx).
These functions are not yet documented in another place as they are both basic and experimental.

So in case you uncover any problem please let us know :)

**Comment by cli0** [comment]
Thanks very much. The API seems to work perfectly so far. Just one more question in relation to the Weisfeiler Lehman kernel interpretation: how exactly (in broad terms) have you defined this kernel? The way I understand it is that I need to provide the kernel with the depth of the subtree exploration and the size of the embedding that I want. But in your interpretation I can't control the embedding and I get a matrix of the shape (n_graphs, n_graphs). I use the following grakel kernel:

`    gk = WeisfeilerLehman(niter=niter, normalize=normalize, base_kernel=VertexHistogram)
`

**Comment by johanesmikhael** [comment]
Hi @ysig , i tried to import networkx graph using the utils provided by API however the kernel does not seems to work with the resulted data. The console said "TypeError: each element of X must have at least one and at most 3 elements". I used the latest version of grakel ( 0.1a5) in python 35 Windows. 

I followed the tutorial in short intro and its fine, but I discovered that when I input the data using edge dictionary format, an error raise like this:

`>>> H2O = {'a': {'b': 1., 'c': 1.}, 'b': {'a': 1}, 'c': {'a': 1.}}
>>> sp_kernel.fit_transform(H2O)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\johan\Miniconda3\envs\python35\lib\site-packages\grakel\graph_kernels.py", line 388, in fit_transform
    K = self.kernel_.fit_transform(X)
  File "C:\Users\johan\Miniconda3\envs\python35\lib\site-packages\grakel\kernels\shortest_path.py", line 381, in fit_transform
    self.fit(X)
  File "C:\Users\johan\Miniconda3\envs\python35\lib\site-packages\grakel\kernels\kernel.py", line 123, in fit
    self.X = self.parse_input(X)
  File "C:\Users\johan\Miniconda3\envs\python35\lib\site-packages\grakel\kernels\shortest_path.py", line 453, in parse_input
    ' one and at most 3 elements\n')
TypeError: each element of X must have at least one and at most 3 elements`

**Comment by ysig** [comment]
Every kernel input is an **iterable of iterables**. That is in your case a `[H20]` and not `H2O`.

**Comment by misterblonde** [comment]
The fit_transform is throwing up the same error for me too. The square brackets didn't resolve it either. Any news on this?
