### ISSUE TITLE
Calculate a default kernel value

### ISSUE THREAD

**Issue by davide1995** [ysig/GraKeL#11]
I was reading this introduction:
https://ysig.github.io/GraKeL/dev/user_manual/longer_introduction.html

I exeuted the following lines:
```
from grakel import GraphKernel
H2O = [[[[0, 1, 1], [1, 0, 0], [1, 0, 0]], {0: 'O', 1: 'H', 2: 'H'}]]
H3O = [[[[0, 1, 1, 1], [1, 0, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0]], {0: 'O', 1: 'H', 2: 'H', 3:'H'}]]
gs_kernel = GraphKernel(kernel=dict(name="graphlet_sampling", n_samples=5))
gs_kernel.fit(H2O)
```
An error occurs on fit method:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/grakel/graph_kernels.py", line 290, in fit
    self.initialize_()
  File "/usr/local/lib/python3.7/site-packages/grakel/graph_kernels.py", line 430, in initialize_
    self.kernel_ = kernel(**params)
TypeError: __init__() got an unexpected keyword argument 'n_samples'
```
I'm using grakel 0.1a5 under python 3.7.1

**Comment by ysig** [comment]
You are right. Documentation at that point is outdated.
`n_samples` is a field of a dictionary that goes under `sampling`.
You can always checkout the given kernel [reference].(https://ysig.github.io/GraKeL/dev/generated/grakel.GraphletSampling.html#grakel.GraphletSampling)

So a correct statement would be:
`gs_kernel = GraphKernel(kernel=dict(name="graphlet_sampling", sampling=dict(n_samples=5)))`

**Comment by ysig** [comment]
Fixed this issue here: https://github.com/ysig/GraKeL/commit/9b436bd115f9018519f0f6f29a03909b22dcacd5
