### ISSUE TITLE
RandomWalk kernel incompatible with SciPy version >=1.14.0

### ISSUE THREAD

**Issue by klausweinbauer** [ysig/GraKeL#111]
**Describe the bug**
The arguments for the function `scipy.sparse.linalg.cg` changed. `tol` was deprecated and got replaced by `rtol` in version 1.14.0 [[1](https://docs.scipy.org/doc/scipy-1.13.1/reference/generated/scipy.sparse.linalg.cg.html)]

**To Reproduce**
```
from grakel.graph import Graph
from grakel.kernels import RandomWalk, RandomWalkLabeled

RandomWalk().fit_transform([Graph([(0, 1)])])
RandomWalkLabeled().fit_transform([Graph([(0, 1)], node_labels={0: 0, 1: 0})])
```
**Error**
`TypeError: cg() got an unexpected keyword argument 'tol'`

I'll provide a PR.

**Comment by ysig** [comment]
@klausweinbauer sorry for the late reply. Thank you! Please merge both requests into one and make them backwards compatible and I will pull them :))

**Comment by klausweinbauer** [comment]
The explicit datatype specification is at least backward compatible with SciPy Version 1.0.0 [[1]](https://docs.scipy.org/doc/scipy-1.0.0/reference/generated/scipy.sparse.csr_matrix.html#scipy.sparse.csr_matrix). For the argument name change, I added the version requirement. Thanks :)
