### ISSUE TITLE
something wrong in the code annotation

### ISSUE THREAD

**Issue by lphcreat** [ysig/GraKeL#12]
[https://ysig.github.io/GraKeL/dev/_modules/grakel/utils.html#graph_from_pandas](url)；
func :graph_from_pandas ;in the third explaining of node_df

**Comment by ysig** [comment]
Fixed this issue here: https://github.com/ysig/GraKeL/commit/9b436bd115f9018519f0f6f29a03909b22dcacd5

Thanks for the feedback
