### ISSUE TITLE
Graph_from_CSV

### ISSUE THREAD

**Issue by misterblonde** [ysig/GraKeL#13]
Hi, 

I'm having the same problem as mentioned in a previous issue of not being able to produce the correct input format, not from a networkX graph nor the CSV file. Both functions itself work fine, but as soon as I try to use the fit_transform(X) it throws an error: 

for graph_from_csv object it throws:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-104-ad1e97392643> in <module>
----> 1 sp_kernel.fit_transform(new_G)

~/anaconda3/envs/py36/lib/python3.6/site-packages/grakel/graph_kernels.py in fit_transform(self, X, y)
    386             K = self.kernel_.transform(X).dot(self.nystroem_normalization_.T)
    387         else:
--> 388             K = self.kernel_.fit_transform(X)
    389 
    390         return K

~/anaconda3/envs/py36/lib/python3.6/site-packages/grakel/kernels/shortest_path.py in fit_transform(self, X, y)
    379         """
    380         self._method_calling = 2
--> 381         self.fit(X)
    382 
    383         # calculate feature matrices.

~/anaconda3/envs/py36/lib/python3.6/site-packages/grakel/kernels/kernel.py in fit(self, X, y)
    121             raise ValueError('`fit` input cannot be None')
    122         else:
--> 123             self.X = self.parse_input(X)
    124 
    125         # Return the transformer

~/anaconda3/envs/py36/lib/python3.6/site-packages/grakel/kernels/shortest_path.py in parse_input(self, X)
    428             elif self._method_calling == 3:
    429                 self._Y_enum = dict()
--> 430             for (idx, x) in enumerate(iter(X)):
    431                 is_iter = isinstance(x, collections.Iterable)
    432                 if is_iter:

~/anaconda3/envs/py36/lib/python3.6/site-packages/grakel/utils.py in graph_from_csv(edge_files, node_files, index_type, directed, sep, as_Graph)
    566             type(edge_files[1]) is not bool or
    567             type(edge_files[2]) not in [bool, None]):
--> 568         edge_files_error()
    569     else:
    570         if edge_files[1]:

~/anaconda3/envs/py36/lib/python3.6/site-packages/grakel/utils.py in edge_files_error()
    553     """
    554     def edge_files_error():
--> 555         raise ValueError('edge_file argument must contain an iterable of strings of edge files, '
    556                          'a bool weight_flag and attributes_flag bool or None')
    557 

ValueError: edge_file argument must contain an iterable of strings of edge files, a bool weight_flag and attributes_flag bool or None

whereas I get the same missing,edge, node labels error as in the other issue for my networkX input graph. Essentially i have a large set of unlabelled binary adjacency matrices as csv files and want to measure their similarity using your kernels. I have already tried the PM kernel in Matlab you developed and it was working like a charm! Thanks for your help.

**Comment by misterblonde** [comment]
when using .graph_from_networkx()

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-106-ad1e97392643> in <module>
----> 1 sp_kernel.fit_transform(new_G)

~/anaconda3/envs/py36/lib/python3.6/site-packages/grakel/graph_kernels.py in fit_transform(self, X, y)
    386             K = self.kernel_.transform(X).dot(self.nystroem_normalization_.T)
    387         else:
--> 388             K = self.kernel_.fit_transform(X)
    389 
    390         return K

~/anaconda3/envs/py36/lib/python3.6/site-packages/grakel/kernels/shortest_path.py in fit_transform(self, X, y)
    379         """
    380         self._method_calling = 2
--> 381         self.fit(X)
    382 
    383         # calculate feature matrices.

~/anaconda3/envs/py36/lib/python3.6/site-packages/grakel/kernels/kernel.py in fit(self, X, y)
    121             raise ValueError('`fit` input cannot be None')
    122         else:
--> 123             self.X = self.parse_input(X)
    124 
    125         # Return the transformer

~/anaconda3/envs/py36/lib/python3.6/site-packages/grakel/kernels/shortest_path.py in parse_input(self, X)
    428             elif self._method_calling == 3:
    429                 self._Y_enum = dict()
--> 430             for (idx, x) in enumerate(iter(X)):
    431                 is_iter = isinstance(x, collections.Iterable)
    432                 if is_iter:

~/anaconda3/envs/py36/lib/python3.6/site-packages/grakel/utils.py in graph_from_networkx(X, node_labels_tag, edge_labels_tag, edge_weight_tag, as_Graph)
    325         nl = nodel_init()
    326         el = edgel_init()
--> 327         nodes, edges = take_ne(G)
    328         print(nodes)
    329         print(edges)

~/anaconda3/envs/py36/lib/python3.6/site-packages/grakel/utils.py in take_ne(graph)
    316     if v2:
    317         def take_ne(graph):
--> 318             return graph.nodes, graph.edges
    319     else:
    320         def take_ne(graph):

AttributeError: 'int' object has no attribute 'nodes'

**Comment by ysig** [comment]
Hi.
Please provide me with the script lines, where you are calling this function, because something doesn't seem right.
Thanks

**Comment by misterblonde** [comment]
Do you have an example anywhere where you don't use a custom dataset such as MUTAG, but your own dataset, so loading in the graphs and using it for ML is a little clearer? 

It works fine for the MUTAG default dataset, but not sure how to get my graphs into the minimum required format, ie. I managed to fix the problem I reported earlier by generating node labels for my graphs which initially didn't have any etc.  and generating the H2O format by hand.

**Comment by ysig** [comment]
Hi,
the functions graph_from_csv and graph_from_networkx are functions that we added on our last package and will be updated (fixed) on the

**Comment by misterblonde** [comment]
Hi ysig,

I created this little sample repos to show you my workaround:
https://github.com/misterblonde/GraKelTest

Kernel Comparison if its 1 vs. 1 works fine, but returns an array with 1 entry. I just flattened the array for now and wrote it all into a new output DataFrame. However this is not ideal. 

I don't know how to improve this. Also none of the selected kernels work without some Dummy atom labels.

**Comment by ysig** [comment]
Hi misterblond,

after reading your code, seems you don't get something right.
Firstly comparing pair-by-pair node labels with a kernel is not suggested even when using the raw values of a kernel (not even the normalized ones).

Please see my  KernelSimilarity function from your file [GraphKernels-bak.py](https://github.com/misterblonde/GraKelTest/blob/master/GraphKernels-bak.py#L61):

```
def KernelSimilarity(new_graphs, node_labels):
    """

    Combines Node Labels and adds them onto graphs which are read in as .csv files
    Builds a similarity matrix which is then saved as a .csv file

    """

    graphs = []
    for ref_index, ref_file in enumerate(new_graphs):

        # Compute Reference Kernel all other Kernels will be compared across the row:
        # Generate graph that all others are compared to in this row:
        df = pd.read_csv(f"{current_path}/{inp_folder}/{ref_file}.csv", header=None)
        G = df.values.tolist()
        # join networkX graph data and fake labels created previously:
        graphs.append([G, node_labels])


    start = time.time()
    out = kernel.fit_transform(graphs)
    end = time.time()
    print("Time needed for Reference Kernel computation (s): ", end - start)

    # Write Matrix to file
    pd.DataFrame(out, index=new_graphs, columns=new_graphs).to_csv(f"{req_kernel}_{inp_folder}_SimilarityKernel.csv", header=True, index=True)

    #####################################################################
```

Concerning labels, for kernels:
- "shortest_path"
- "pyramid_match"
- "random_walk"
you are using set the `with_labels` argument to False, if you don't want to use node-labels.

Now "neighborhood_hash" functions only with node-labels.

All this can be found here:
[](https://ysig.github.io/GraKeL/dev/graph_kernel.html
)
I hope this relieves your struggle.

**Comment by misterblonde** [comment]
Thanks a lot ysig! That was the easy answer I was looking for. I knew my workaround wasn't great, hence my "report issue" haha. Cheers so much! I hope I can put it to good use now!

**Comment by shambelFente** [comment]
HI everyone
i was trying to split list of grakel graph using scikit learn  train_test_split. but i got the following error. could you suggest me the possible mistakes.

TypeError: "Singleton array array(<generator object graph_from_networkx at 0x000002301CB45820>,
      dtype=object) cannot be considered a valid collection."
![Capture](https://user-images.githubusercontent.com/57561374/116754883-c915aa80-aa09-11eb-94d2-b22e46fcc02c.PNG)

**Comment by ysig** [comment]
`graph_from_networkx` returns a generator. You should apply a list to it in
order for it to work with sklearn.
