### ISSUE TITLE
Including node attributes in GraKel

### ISSUE THREAD

**Issue by sbhttchryy** [ysig/GraKeL#23]
Is there any way to include node attributes (like a feature vector for each node) for the graph in GraKel?

**Comment by giannisnik** [comment]
Dear @sbhttchryy ,

Yes you can. Have a look at this example: https://ysig.github.io/GraKeL/0.1a7/documentation/introduction.html#assigning-labels-attributes-to-nodes

**Comment by sbhttchryy** [comment]
Thank you very much
