### ISSUE TITLE
full documentation link down

### ISSUE THREAD

**Issue by zsxing99** [ysig/GraKeL#24]
The link towards documentation provided by README is currently down. Any fix or backup?

**Comment by giannisnik** [comment]
Hi @zsxing99 . We have merged the develop branch into the master branch. The documentation is available at this link: https://ysig.github.io/GraKeL/latest/ . The documentation for the upcoming 0.1a7 version is available at: https://ysig.github.io/GraKeL/0.1a7/ .

**Comment by zsxing99** [comment]
Thanks!
