### ISSUE TITLE
MultiscaleLaplacianFast parse_input doesn't accept length one input

### ISSUE THREAD

**Issue by YemanBrhane** [ysig/GraKeL#39]
Implementation parse_input doesn't consider when every input is of length one with data type graph. To be consistent with the other kernels, I have added                 

elif type(x) is Graph:
                    pass

**Comment by ysig** [comment]
Thanks for your feedback!
Fixed in latest commit.
https://github.com/ysig/GraKeL/commit/f67ddd036a8a2c2815070d333d382a84b2157aab
