### ISSUE TITLE
Dealing with multiple sets of continuous attributes?

### ISSUE THREAD

**Issue by SylvainTakerkart** [ysig/GraKeL#41]
Hi there!

First, nice job with GraKel ;) It took me very little time to get my graphs into a format that can be handled by GraKel (thanks to the networkx import method and the corresponding example)!

My graphs (computed from some brain imaging data) have multiple vector-valued attributes on each node... Can any of the kernels availabe in GraKel deal with this? (I of course have the solution of concatenating the different vectors into one, but I'm just wondering whether there's  a cleaner solution...) Or any kernel in general?

Thanks,

Sylvain

**Comment by giannisnik** [comment]
Thank you @SylvainTakerkart . Unfortunately, there are no kernels that can handle graphs whose nodes are assigned multiple vector-valued attributes (2d matrices). As you mentioned, you can concatenate these vectors and then employ some kernel that takes them into account (e.g., GraphHopper, PropagationAttr, MultiscaleLaplacianFast, SubgraphMatching).

**Comment by SylvainTakerkart** [comment]
OK, thanks for your answer!
