### ISSUE TITLE
joblib raised Deprecation Error

### ISSUE THREAD

**Issue by EchoShoot** [ysig/GraKeL#44]
DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)

cannot import name 'joblib' from 'sklearn.externals

**Comment by zsxing99** [comment]
```c:\python38\lib\site-packages\grakel\kernels\kernel.py in <module>
     12 from sklearn.exceptions import NotFittedError
     13 from sklearn.utils.validation import check_is_fitted
---> 14 from sklearn.externals import joblib
     15 
     16 from grakel.graph import Graph

ImportError: cannot import name 'joblib' from 'sklearn.externals' 
```

I think it has been removed and I am unable to use it.

**Comment by ysig** [comment]
This error was solved in the latest commit.
It will be available on pip, on a future version of grakel.
The workaround was to install joblib and import it as a package.

Στις Κυρ, 31 Μαΐ 2020 στις 2:02 π.μ., ο/η Zesheng Xing <
notifications@github.com> έγραψε:

**Comment by SylvainTakerkart** [comment]
Hi,
I'm getting back into using grakel after a few months... And I'm getting the same error...
Do you have any idea when the version available on pip will integrate this fix? It'd be very helpful coz I think all users are impacted, no? ;)
Cheers,
Sylvain

**Comment by ysig** [comment]
Hi Sylvain,

yes we hope inside this month we will upload the new version.
We have added a new kernel and have a small bug.
As soon as we fix this we will upload it.

y

**Comment by SylvainTakerkart** [comment]
great, thanks ;)
