### ISSUE TITLE
implementation of EMD Kernel 

### ISSUE THREAD

**Issue by zhuo931077127** [ysig/GraKeL#46]
Hi, this Graph Kernel repo is perfect. Could you provide the code implementation of EMD Kernel, which proposed in "Matching Node Embeddings for Graph Similarity" AAAI'17?

**Comment by giannisnik** [comment]
Hi @zhuo931077127 , EMD is not a kernel. Thus, it is not contained in the GraKeL package. You can find the Matlab implementation of the Earth Mover’s Distance approach in the following link: https://www.dropbox.com/sh/4dgthm4p87luyi4/AAAtGBGt1LP12yAkyaEOIyhXa?dl=0 . The code creates the similarity matrix, and then, to perform classification, you can use the extension of the SVM for indefinite kernels from the following link or you can use the conventional SVM (which is not however guaranteed to reach the optimal solution): http://www.di.ens.fr/~aspremon/ZIP/IndefiniteSVM.zip
