### ISSUE TITLE
How to get the matching graph?

### ISSUE THREAD

**Issue by wjd92** [ysig/GraKeL#51]
We now could use `transform` function to measure similarity between two graphs, but how to get the matching graph?
Could we get corresponding nodes and edges in comparing graphs?
Any suggestions?

**Comment by ysig** [comment]
Very few graph kernels solve a matching problem.
In a nutshell, most of them just calculate features for graphs in the input and then calculate a dot product between features, i.e. a similarity metric.

Could you explain what you describe in more detail?
