### ISSUE TITLE
Documentation returns Error 404

### ISSUE THREAD

**Issue by JosuaStadelmaier** [ysig/GraKeL#55]
When going to [https://ysig.github.io/GraKeL/0.1a8](https://ysig.github.io/GraKeL/0.1a8), I get a "File not found" error.

**Comment by giannisnik** [comment]
Hi @JosuaStadelmaier 

Indeed the documentation is not currently available. We will fix this as soon as possible. In the meantime, you can have a look at the previous version's documentation (very similar) here: https://ysig.github.io/GraKeL/0.1a7/

**Comment by JosuaStadelmaier** [comment]
Hi @giannisnik,
Thank you very much for this helpful hint.

**Comment by ysig** [comment]
sphinxcontrib-bibtex updated its version and I had to constrain it to 1.0.
Website is restored.
