### ISSUE TITLE
RuntimeWarning: invalid value encountered in divide

### ISSUE THREAD

**Issue by xia0pin9** [ysig/GraKeL#6]
Got the following RuntimeWarning when using graphlet_sampling kernel:

```
/usr/local/lib/python2.7/site-packages/grakel/kernels/graphlet_sampling.py:313: RuntimeWarning: invalid value encountered in divide
  return np.divide(km, np.sqrt(np.outer(self._X_diag, self._X_diag)))
```

It is probobally caused by INF/NaN value. Not a major problem, but may correspond to some edge cases.

**Comment by ysig** [comment]
This is what happens in some kernels when having to do with corner cases (i.e. empty graphs etc).
It is on the hand of the user to deal with the Inf/NaN on the result where the standard approach is to apply the [`numpy.nan_to_num`](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.nan_to_num.html) on the resulting kernel matrix.
