### ISSUE TITLE
pynauty

### ISSUE THREAD

**Issue by pdobsan** [ysig/GraKeL#60]
Hi,

I am the author of `pynauty`. Due to some github magic I discovered that at some stage you used `pynauty`. This is just to let you know that I have recently moved the package to [Github - pynauty]( https://github.com/pdobsan/pynauty) and updated it. I also made it available from [PyPi - pynauty](https://pypi.org/project/pynauty/), many binary wheels are also provided for Linux and macOS platforms.

**Comment by ysig** [comment]
Hi sir,

great honor.

Unfortunately, we have removed pynauty dependency in favor of [Bliss](http://www.tcs.hut.fi/Software/bliss/) which we also hardcoded so it compiles with windows.
The thing is, that we use it to compute isomorphism for one kernel, which makes the kernel slow and thus this mainly exists for educational purposes - benchmarking (it's not something people often use).
We thus preferred to make cpython extension that compiles in all devices and that it is stable.

Thank you :)
