### ISSUE TITLE
GraphHopper: data type must provide an itemsize

### ISSUE THREAD

**Issue by shelusb** [ysig/GraKeL#63]
Hi,
I tried running the GH kernel, but got this error: data type must provide an itemsize:

> anaconda3\lib\site-packages\grakel\graph.py:312: UserWarning: changing format from "adjacency" to "all"
>   warnings.warn('changing format from "adjacency" to "all"')
> Traceback (most recent call last):
>   File "test.py", line 71, in <module>
>     t11 = sp_kernel2.fit_transform([g1])
>   File "anaconda3\lib\site-packages\grakel\kernels\kernel.py", line 197, in fit_transform
>     km = self._calculate_kernel_matrix()
>   File "anaconda3\lib\site-packages\grakel\kernels\kernel.py", line 231, in _calculate_kernel_matrix
>     K[i, i] = self.pairwise_operation(x, x)
>   File "anaconda3\lib\site-packages\grakel\kernels\graph_hopper.py", line 261, in pairwise_operation
>     return self.metric_((xp.reshape(xp.shape[0], m_sq),) + x[1:],
>   File "anaconda3\lib\site-packages\grakel\kernels\graph_hopper.py", line 282, in linear_kernel
>     NA_linear_kernel = np.dot(NA_i, NA_j.T)
>   File "<__array_function__ internals>", line 5, in dot
> ValueError: data type must provide an itemsize

Here is my code (which works fine with the shortest path kernel):
```
from grakel import Graph
from grakel import GraphKernel
#sp_kernel = GraphKernel(kernel="shortest_path")
from grakel.kernels import ShortestPath, GraphHopper
g1_edges = {(1, 2): 1, (1, 3): 1, (2, 1): 1, (3, 1): 1}
g1_edge_labels = {(1, 2): [1], (1, 3): [2], (2, 1): [1], (3, 1): [2]}
g1_node_labels = {1:'1',2:'2',3:'3'}
g1 = Graph(g1_edges, node_labels=g1_node_labels, edge_labels=g1_edge_labels)

g2_edges = {(1, 2): 1, (1, 3): 1, (2, 1): 1, (3, 1): 1}
g2_edge_labels = {(1, 2): [1], (1, 3): [2], (2, 1): [2], (3, 1): [1]}
g2_node_labels = {1:'1',2:'2',3:'3'}
g2 = Graph(g2_edges, node_labels=g2_node_labels, edge_labels=g2_edge_labels)

sp_kernel2 = GraphHopper(normalize=True)
t11 = sp_kernel2.fit_transform([g1])
t12 = sp_kernel2.transform([g2])
print(t11)
print(t12)
```

I also tried it with edge labels instead of edge attributes, but it didn't help. The issue happens in this line:
sp_kernel2 = GraphHopper(normalize=True)

**Comment by giannisnik** [comment]
Hi @shelusb ,

The GraphHopper kernel expects the nodes to be annotated with continuous attributes and not with discrete labels. You just need to replace the lines where you initialize the labels with this:
`g1_node_labels = {1:[1.0,0.0,0.0],2:[0.0,1.0,0.0],3:[0.0,0.0,1.0]}`
and 
`g2_node_labels = {1:[1.0,0.0,0.0],2:[0.0,1.0,0.0],3:[0.0,0.0,1.0]}`
in case your attributes/labels are categorical.

Furthermore, I can see that you also assign labels to the edges of the graphs. I thus need to let you know that the GraphHopper kernel ignores these labels (see this: https://ysig.github.io/GraKeL/0.1a8/graph_kernel.html).

**Comment by gitshelmi** [comment]
@giannisnik thanks for your reply.
My edge labels/attributes are all continuous values.
So, my adj matrix is like:
[?   0.2   0.4
[0.2 ?    0
[0.4  0   ?]
?: I think it should be 0 because I don't have recursive/self edges.
0: I mean there is no edge between those two nodes: for example no node between the second and third node.
0.2: shows the weight on the edge, for example the edge between the first and second node has the weight of 0.2.

How would you initialize this graph?

And no names in graph hopper do matter, right? For example, it distinguishes the node between nodes 1 and 2 and 1 and 3 although if they have the same weight, right?

**Comment by giannisnik** [comment]
@shelusb There are some kernels that can take edge weights into account such as the [Pyramid Match](https://ysig.github.io/GraKeL/0.1a8/kernels/pyramid_match.html) kernel and the [Multiscale Laplacian](https://ysig.github.io/GraKeL/0.1a8/kernels/multiscale_laplacian.html) kernel.

This topic has been discussed in the past. See this: https://github.com/ysig/GraKeL/issues/37
