### ISSUE TITLE
How to get mediate feature of graphs

### ISSUE THREAD

**Issue by LittleWhite-Hai** [ysig/GraKeL#64]
Thank for your implementation and detailed documentation! 
The graph kernels produce a similarity matrix of graphs, and it's a dot product of graph features.I want to know how to do to get these features.
I have studied the implementation of Weisfeiler Lehman kernel for half of a day and can't figure out so far :(

**Comment by giannisnik** [comment]
Hi @LittleWhite-Hai ,

For some kernels where the mapping to the feature space is explicit, you can indeed obtain such features. For instance, for the Weisfeiler-Lehman subtree kernel, you can obtain the features for the different iterations as follows:
```
from grakel.datasets import fetch_dataset
from grakel.kernels import WeisfeilerLehman, VertexHistogram

dataset = fetch_dataset("MUTAG", verbose=False)
Gs = dataset.data
wl_kernel = WeisfeilerLehman(n_iter=3,  base_graph_kernel=VertexHistogram)
wl_kernel.fit(Gs)
features_it_0 = wl_kernel.X[0].X
features_it_1 = wl_kernel.X[1].X
features_it_2 = wl_kernel.X[2].X
features_it_3 = wl_kernel.X[2].X
```
In this example, `features_it_0`, `features_it_1`, `features_it_2`, `features_it_3` are all sparse matrices where the number of rows is equal to the number of graphs (i.e., `len(Gs)`) and the number of columns is equal to the number of different labels assigned to the nodes of all graphs at that iteration.
