### ISSUE TITLE
Is there a best practice when computations are done in a cluster?

### ISSUE THREAD

**Issue by ragnarlevi** [ysig/GraKeL#68]
Thank for your the package!

I wanted to try to speed up the fitting process on a cluster and I was wondering if there are any best practices in doing so? For example does GraKel have multiprocessing options?

The job is submitted via SLURM.

**Comment by ysig** [comment]
Hi @ragnarlevi. Nice question.

So Grakel supports basic parallelism using joblib whenever it's possible.
On the other hand for some kernels are written only using numpy vectorized operations, which follow low level parallelism through LAPACK.

We haven't made a scaling study for GraKeL in cluster, so please keep us posted about the experiments you will make and any observation you may have.
