### ISSUE TITLE
The newest document is missing

### ISSUE THREAD

**Issue by Huang-da-mao** [ysig/GraKeL#70]
**Describe the bug**
Same as the title.

The link will be redirected automatically to the newest [website](https://ysig.github.io/GraKeL/0.1a8) when accessed.
However, it gives a 404 error.
The [older one](https://ysig.github.io/GraKeL/0.1a7) is valid.

**Comment by giannisnik** [comment]
Hi @onlyacat ,

Thanks for letting us know. We have fixed the issue and it is now accessible.

**Comment by Huang-da-mao** [comment]
> Hi @onlyacat ,
> 
> Thanks for letting us know. We have fixed the issue and it is now accessible.

Thanks!
