### ISSUE TITLE
initialization of self.mu_ in random_walk.py

### ISSUE THREAD

**Issue by JuliusSchwartz** [ysig/GraKeL#71]
**Describe the bug**
 
the manner in which self.mu_ is initialized in the RandomWalk class looks like it's being done the wrong way around - line 105 of random_walk.py looks like it should read `if self.kernel_type == "exponential":` and line 112 looks like it should read `self.mu_.append(power/fact)`

**Comment by ysig** [comment]
@giannisnik

**Comment by giannisnik** [comment]
Hi @JuliusSchwartz ,

Thank you for spotting these issues and letting us know. Indeed you are right. We will fix them in the next version.
