### ISSUE TITLE
use of ‘WeisfeilerLehman’

### ISSUE THREAD

**Issue by happysnzy** [ysig/GraKeL#76]
My understanding is that ‘WeisfeilerLehman’ must be used in conjunction with a base graph kernel, such as 'VertexHistogram'. If I want to use graph kernel  ‘WeisfeilerLehman’ alone, what should I do? Is the following statement correct?
‘gk = WeisfeilerLehman(n_iter=50, base_graph_kernel=WeisfeilerLehman, normalize=True)’

**Comment by giannisnik** [comment]
Hi @happysnzy ,

There is no  ‘WeisfeilerLehman’ kernel alone. Usually when one speaks about the ‘WeisfeilerLehman’ kernel alone, she refers to the Weisfeiler-Lehman subtree kernel (i.e., 'VertexHistogram' as the base kernel). Therefore, the statement you provided is not correct.
