### ISSUE TITLE
How to use the edge weight information of a graph？

### ISSUE THREAD

**Issue by happysnzy** [ysig/GraKeL#77]
First of all thank you very much, Grakel really helped me a lot with my research. But I'm currently running into a problem. I want to compute graph similarity using Grakel, such as random walk kernel. But I read the introduction in the document (https://ysig.github.io/GraKeL/0.1a8/graph_kernel.html), these kernels do not use the edge weight information of the graph. I sincerely want to know how I can take advantage of the weighted edges of the graphs.

**Comment by ysig** [comment]
You can use weight information if you add it in the agacency matrix.

**Comment by giannisnik** [comment]
Hi @happysnzy ,
This has been discussed in the past. See this: https://github.com/ysig/GraKeL/issues/37
