### ISSUE TITLE
Can't install on Windows 10, keep getting same error

### ISSUE THREAD

**Issue by preslaff** [ysig/GraKeL#99]
**Can't install the package in WIndows 10. I keep getting this error:**

building 'grakel.kernels._isomorphism.intpybliss' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Tried with different environements:**
Python 3.5
Python 3.6
Python 3.10
Python 3.11

**Comment by ysig** [comment]
Can you share the full log of when you install it? Normally you shouldn't have that issue.

**Comment by preslaff** [comment]
Thank you, it worked fine on python 3.10. It happens that the problem was with versions 3.6 and 3.11. With python 3.10 It works with the default grakel package. Thanks again!
